# Generated by Django 5.0.1 on 2024-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=85, unique=True)),
                ('printed_out', models.BooleanField(default=False)),
                ('id_sku', models.IntegerField(default=0)),
                ('id_party', models.IntegerField(default=0)),
                ('date_loaded', models.DateTimeField(auto_now_add=True)),
                ('date_output', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
