# Generated by Django 5.0.1 on 2024-01-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startPrintLabels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FileLoad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('cut', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('prefix', models.CharField(default='', max_length=30)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='codes',
            name='id_party',
        ),
        migrations.AddField(
            model_name='codes',
            name='id_parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startPrintLabels.parts'),
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gtin', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('prefix', models.CharField(default='', max_length=5)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startPrintLabels.company')),
                ('id_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startPrintLabels.groups')),
            ],
        ),
        migrations.AlterField(
            model_name='codes',
            name='id_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startPrintLabels.sku'),
        ),
    ]
