# Generated by Django 5.0.1 on 2024-01-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPrintLabels', '0002_company_fileload_groups_parts_remove_codes_id_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='id_parts',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='id_sku',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='id_company',
        ),
        migrations.DeleteModel(
            name='FileLoad',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='id_groups',
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
